# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Create Subscription
POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Starter",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }

### Get Subscription
@subscriptionId=6727B548-5DC1-43B4-8A67-40F9E270D49D
GET {{host}}/Subscriptions/{{subscriptionId}}

### Get Subscription - Starter
@starterSubscriptionId=5FA0F9AD-E0CE-41BA-ACA3-2987E0A16C37
GET {{host}}/Subscriptions/{{starterSubscriptionId}}

### Subscription not found
@subscriptionIdNotFound=bbf5b8fe-9407-427e-a2d4-0a1a31554735
GET {{host}}/Subscriptions/{{subscriptionIdNotFound}}