# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Create Subscription
@createrId=05049f14-5bb0-4bfd-8cb0-f61d92ea3559
@subscriptionId=CE82E307-2C67-4933-BECA-001915F038AF	
@gymId=FF3EADFE-5B5D-4849-8CFD-B7D13FF7BF38
@roomId=04634798-c658-498a-b47f-14dea35357bb
### Create Subscription
POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Starter",
    "AdminId": "{{createrId}}"
}


### Get Subscription
GET {{host}}/Subscriptions/{{subscriptionId}}


### Create Gym
POST {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json

{
    "Name": "Jeff's gym"
}

### List Gyms
GET {{host}}/subscriptions/{{subscriptionId}}/gyms

### Get Gym
GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}

### Create Room
POST {{host}}/gyms/{{gymId}}/rooms
Content-Type: application/json

{
    "Name": "A room"
}

### Delete Room
DELETE {{host}}/gyms/{{gymId}}/rooms/{{roomId}}

### Delete Gym
DELETE {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}

### Delete Subscription 
DELETE {{host}}/Subscriptions/{{subscriptionId}}